Improve(code): Improved the code
redis-developer/introducing-the-geosearch-command pull request #21
Opened 2022-10-24 22:27 UTC by RajputUsman

2022-10-24 22:48 UTC, simonprickett requested changes

2022-10-24 22:48 UTC, simonprickett commented on load_stations.py
> +    pipeline.hset(station_key, station_data)
Did you test run this?  It errors:

```
$ python load_stations.py
Traceback (most recent call last):
  File "/Users/simonprickett/source/github/introducing-the-geosearch-command/load_stations.py", line 44, in <module>
    responses = pipeline.execute()
  File "/Users/simonprickett/source/github/introducing-the-geosearch-command/venv/lib/python3.10/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/Users/simonprickett/source/github/introducing-the-geosearch-command/venv/lib/python3.10/site-packages/redis/client.py", line 3949, in _execute_pipeline
    all_cmds = connection.pack_commands([args for args, _ in commands])
  File "/Users/simonprickett/source/github/introducing-the-geosearch-command/venv/lib/python3.10/site-packages/redis/connection.py", line 801, in pack_commands
    for chunk in self.pack_command(*cmd):
  File "/Users/simonprickett/source/github/introducing-the-geosearch-command/venv/lib/python3.10/site-packages/redis/connection.py", line 775, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/Users/simonprickett/source/github/introducing-the-geosearch-command/venv/lib/python3.10/site-packages/redis/connection.py", line 119, in encode
    raise DataError("Invalid input of type: '%s'. Convert to a "
redis.exceptions.DataError: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.
```

2022-10-25 09:38 UTC, SuzeShardlow commented
@RajputUsman please see @simonprickett's comments in his review above ^^ :)

2022-10-25 17:24 UTC, SuzeShardlow commented
@RajputUsman please let me know if you are still working on this.  If not, I will close the PR.  Thanks!

2022-10-25 18:14 UTC, RajputUsman commented
Thanks, I tried to resolve with docker, but it didn't work out.

2022-10-25 18:14 UTC, closed without merging